#
# LuaDist Travis-CI Hook
#

notifications:
  email: false

# We assume Ruby environments
language: Ruby
rvm:
  - 2.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential xorg-dev libudev-dev libts-dev libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev libopenal-dev libogg-dev libvorbis-dev libaudiofile-dev libpng12-dev libfreetype6-dev libusb-dev libdbus-1-dev zlib1g-dev libdirectfb-dev
  - sudo apt-get install -y libgtk-3-0
  - gem update --system
  - gem --version

# Install dependencies
install:
  - sudo apt-get install -y ruby-dev
  - gem install bundler
  - gem install

# Build the module
script:
  - rake
  - CODECLIMATE_REPO_TOKEN=dcf837f47a43d432f10e70d3dd3764e8ee196e6b9c109f399e2c718ae88b63d7 bundle exec codeclimate-test-reporter

# Only watch the master branch
branches:
  only:
    - master

addons:
  code_climate:
    repo_token: dcf837f47a43d432f10e70d3dd3764e8ee196e6b9c109f399e2c718ae88b63d7
